language: python
python:
  - "3.6"
install:
  - python setup.py install
script:
  - python version_parser/test.py



deploy:
  provider: pypi
  user: $username
  password: $password
  on:
    branch: master
